server.port=8080

spring.cloud.azure.active-directory.enabled=true

spring.cloud.azure.active-directory.credential.client-id=97fd6d32-e248-449e-9862-b31ee3e937ec

spring.cloud.azure.active-directory.app-id-uri=api://97fd6d32-e248-449e-9862-b31ee3e937ec

spring.cloud.azure.active-directory.profile.tenant-id=fe70fa16-a45c-4810-b613-80f2842db999

spring.security.oauth2.resourceserver.jwt.audiences=97fd6d32-e248-449e-9862-b31ee3e937ec